# Staging environment - enabled services configuration
#
# This file overrides the default enabled.yaml for the staging environment.
# Staging should closely mirror production setup for testing.
#
# Note: All keys should be explicitly defined to avoid parsing errors.
# If a service is not listed here, the default from config/enabled.yaml applies.

enabled:
  # Monitoring stack
  prometheus: true
  grafana: true

  # Networking
  cloudflared: true
  tailscaleOperator: true

  # Secrets management
  externalSecrets: true

  # CI/CD
  githubRunner: false  # Can be enabled to test GitHub Actions runner deployments in staging

  # Additional services
  certManager: true  # Enable to test certificate management
  velero: false  # Backups optional in staging
