helmDefaults:
  wait: true
  timeout: 600
  recreatePods: false
  force: false

{{ readFile "config/repositories.yaml.gotmpl" | tpl }}

{{ readFile "config/enabled.yaml" }}

{{ readFile "config/releases.yaml.gotmpl" | tpl }}
