# Secret Rotation Tracker
# Update dates after each rotation following procedures in SECRETS.md

age_key:
  last_rotated: "2024-12-05"  # YYYY-MM-DD format - Update after quarterly rotation
  rotation_frequency_days: 90
  next_rotation: "2025-03-05"  # Automatically calculated: last_rotated + 90 days

ansible_vault:
  last_rotated: "2024-12-05"  # YYYY-MM-DD format - Update after annual rotation
  rotation_frequency_days: 365
  next_rotation: "2025-12-05"  # Automatically calculated: last_rotated + 365 days

# Rotation History (for audit trail)
rotation_history:
  - type: age_key
    date: "2024-12-05"
    rotated_by: "initial-setup"
    notes: "Initial age key setup"
  
  - type: ansible_vault
    date: "2024-12-05"
    rotated_by: "initial-setup"
    notes: "Initial Ansible Vault setup"

# Notes:
# - Update this file immediately after completing any secret rotation
# - Run the secret-expiration-check workflow to verify dates
# - Keep rotation_history for audit purposes
