# Checkov Configuration
# https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

# Skip specific checks that are not applicable or are false positives
# Format: CKV_<FRAMEWORK>_<CHECK_NUMBER>
skip-check:
  # Kubernetes checks to skip
  - CKV_K8S_43  # Image should use digest instead of tag - not practical for Helm charts
  
  # Helm checks to skip (add as needed)
  # - CKV_HELM_1
  
  # Ansible checks to skip (add as needed)
  # - CKV_ANSIBLE_1

# Framework-specific configurations
framework:
  - kubernetes
  - helm
  - ansible

# Severity threshold - fail only on HIGH and CRITICAL
# Options: CRITICAL, HIGH, MEDIUM, LOW
soft-fail: true
hard-fail-on: 
  - CRITICAL
  - HIGH

# Compact output for better readability
compact: true

# Show resource IDs that failed checks
output-bc-ids: true

# Download external modules for scanning
download-external-modules: true

# Directories to skip
skip-path:
  - .git
  - .github
  - node_modules
  - venv
  - .venv

# Enable specific checks (optional)
# check:
#   - CKV_K8S_1
#   - CKV_K8S_2

# Custom policies directory (if you have custom policies)
# external-checks-dir: 
#   - ./custom-policies

# Baseline file to compare against (optional)
# baseline: checkov-baseline.json
