# SOPS Configuration
# This file defines encryption rules for secrets management
# See: https://github.com/mozilla/sops

creation_rules:
  # Default rule: Encrypt all files with age
  # IMPORTANT: Replace this placeholder with your actual age public key!
  # Generate your key with: age-keygen -o ~/.config/sops/age/keys.txt
  # View your public key with: cat ~/.config/sops/age/keys.txt | grep "public key:"
  - path_regex: \.enc\.yaml$
    age: >-
      age1REPLACEME_YOUR_AGE_PUBLIC_KEY_GOES_HERE_xxxxxxxxxxxxxxxxxxxx
    encrypted_regex: ^(data|stringData)$

  # Environment-specific rules
  - path_regex: helmfile/environments/prod/.*\.enc\.yaml$
    age: >-
      age1REPLACEME_YOUR_AGE_PUBLIC_KEY_GOES_HERE_xxxxxxxxxxxxxxxxxxxx
    encrypted_regex: ^(data|stringData|password|token|key|secret|credentials)$

  - path_regex: helmfile/environments/staging/.*\.enc\.yaml$
    age: >-
      age1REPLACEME_YOUR_AGE_PUBLIC_KEY_GOES_HERE_xxxxxxxxxxxxxxxxxxxx
    encrypted_regex: ^(data|stringData|password|token|key|secret|credentials)$

  - path_regex: helmfile/environments/dev/.*\.enc\.yaml$
    age: >-
      age1REPLACEME_YOUR_AGE_PUBLIC_KEY_GOES_HERE_xxxxxxxxxxxxxxxxxxxx
    encrypted_regex: ^(data|stringData|password|token|key|secret|credentials)$

  # Helm values files that contain secrets
  - path_regex: helmfile/values/.*-secrets\.enc\.yaml$
    age: >-
      age1REPLACEME_YOUR_AGE_PUBLIC_KEY_GOES_HERE_xxxxxxxxxxxxxxxxxxxx
    encrypted_regex: ^(.*password.*|.*token.*|.*key.*|.*secret.*|.*credentials.*)$

# Important Notes:
# 1. Replace the placeholder age public key with your actual key from ~/.config/sops/age/keys.txt
# 2. Keep your age private key (~/.config/sops/age/keys.txt) secure and backed up
# 3. Add it to GitHub Secrets as SOPS_AGE_KEY for CI/CD workflows
# 4. Never commit unencrypted secrets to Git
# 5. Use .enc.yaml extension for all encrypted files
# 6. Store the private key securely (password manager, vault, etc.)
#
# Usage:
# - Encrypt: sops -e secrets.yaml > secrets.enc.yaml
# - Decrypt: sops -d secrets.enc.yaml
# - Edit: sops secrets.enc.yaml
# - Deploy: sops -d secrets.enc.yaml | kubectl apply -f -
