# Example Cloudflared Tunnel Credentials (Encrypted with SOPS)
#
# This is an EXAMPLE file showing the structure of encrypted Cloudflared credentials.
# To create your actual encrypted secret:
#
# 1. Create the tunnel:
#    cloudflared tunnel create infrastructure-tunnel
#
# 2. Create plaintext secret:
#    kubectl create secret generic cloudflared-credentials \
#      --from-file=credentials.json=$HOME/.cloudflared/<TUNNEL-ID>.json \
#      --dry-run=client -o yaml > cloudflared-credentials.yaml
#
# 3. Encrypt with SOPS:
#    sops -e cloudflared-credentials.yaml > cloudflared-credentials.enc.yaml
#
# 4. Delete plaintext and original credentials:
#    rm cloudflared-credentials.yaml
#    shred -u $HOME/.cloudflared/<TUNNEL-ID>.json
#
# 5. Deploy:
#    sops -d cloudflared-credentials.enc.yaml | kubectl apply -f -

apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflare
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:EXAMPLE_ENCRYPTED_DATA_REPLACE_WITH_REAL_SOPS_ENCRYPTION,iv:EXAMPLE_IV,tag:EXAMPLE_TAG,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            EXAMPLE_AGE_ENCRYPTED_FILE_HEADER
            REPLACE_THIS_WITH_REAL_SOPS_ENCRYPTION
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T10:00:00Z"
    mac: ENC[AES256_GCM,data:EXAMPLE_MAC,iv:EXAMPLE_IV,tag:EXAMPLE_TAG,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
