# Example GitHub Runner Secrets (Encrypted with SOPS)
#
# This is an EXAMPLE file showing the structure of encrypted GitHub runner secrets.
# To create your actual encrypted secrets:
#
# 1. Get GitHub runner token:
#    - Go to https://github.com/OWNER/REPO/settings/actions/runners/new
#    - Or use GitHub CLI: gh api /repos/OWNER/REPO/actions/runners/registration-token
#
# 2. Get Tailscale auth key:
#    - Go to https://login.tailscale.com/admin/settings/keys
#    - Create with: Reusable=yes, Ephemeral=yes, Tags=tag:k8s,tag:ci
#
# 3. Create plaintext secret file:
#    cat > github-runner-secrets.yaml <<EOF
#    apiVersion: v1
#    kind: Secret
#    metadata:
#      name: github-runner-secrets
#      namespace: github-runner
#    type: Opaque
#    stringData:
#      github-token: "YOUR_GITHUB_TOKEN"
#      tailscale-authkey: "tskey-auth-YOUR_TAILSCALE_KEY"
#    EOF
#
# 4. Encrypt with SOPS:
#    sops -e github-runner-secrets.yaml > github-runner-secrets.enc.yaml
#
# 5. Delete plaintext:
#    rm github-runner-secrets.yaml
#
# 6. Deploy:
#    sops -d github-runner-secrets.enc.yaml | kubectl apply -f -

apiVersion: v1
kind: Secret
metadata:
    name: github-runner-secrets
    namespace: github-runner
type: Opaque
stringData:
    github-token: ENC[AES256_GCM,data:EXAMPLE_ENCRYPTED_GITHUB_TOKEN,iv:EXAMPLE_IV,tag:EXAMPLE_TAG,type:str]
    tailscale-authkey: ENC[AES256_GCM,data:EXAMPLE_ENCRYPTED_TAILSCALE_KEY,iv:EXAMPLE_IV,tag:EXAMPLE_TAG,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            EXAMPLE_AGE_ENCRYPTED_FILE_HEADER
            REPLACE_THIS_WITH_REAL_SOPS_ENCRYPTION
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T10:00:00Z"
    mac: ENC[AES256_GCM,data:EXAMPLE_MAC,iv:EXAMPLE_IV,tag:EXAMPLE_TAG,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|token|key|secret|credentials)$
    version: 3.8.1
