# Example Monitoring Secrets (Encrypted with SOPS)
#
# This is an EXAMPLE file showing the structure of encrypted monitoring secrets.
# To create your actual encrypted secrets:
#
# 1. Generate strong passwords:
#    GRAFANA_PASSWORD=$(openssl rand -base64 32)
#    ALERTMANAGER_PASSWORD=$(openssl rand -base64 32)
#
# 2. Create plaintext secret file:
#    cat > monitoring-secrets.yaml <<EOF
#    apiVersion: v1
#    kind: Secret
#    metadata:
#      name: monitoring-secrets
#      namespace: monitoring
#    type: Opaque
#    stringData:
#      grafana-admin-password: "$GRAFANA_PASSWORD"
#      alertmanager-admin-password: "$ALERTMANAGER_PASSWORD"
#    EOF
#
# 3. Encrypt with SOPS:
#    sops -e monitoring-secrets.yaml > monitoring-secrets.enc.yaml
#
# 4. Delete plaintext:
#    rm monitoring-secrets.yaml
#
# 5. Deploy:
#    sops -d monitoring-secrets.enc.yaml | kubectl apply -f -

apiVersion: v1
kind: Secret
metadata:
    name: monitoring-secrets
    namespace: monitoring
type: Opaque
stringData:
    grafana-admin-password: ENC[AES256_GCM,data:EXAMPLE_ENCRYPTED_GRAFANA_PASSWORD,iv:EXAMPLE_IV,tag:EXAMPLE_TAG,type:str]
    alertmanager-admin-password: ENC[AES256_GCM,data:EXAMPLE_ENCRYPTED_ALERTMANAGER_PASSWORD,iv:EXAMPLE_IV,tag:EXAMPLE_TAG,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            EXAMPLE_AGE_ENCRYPTED_FILE_HEADER
            REPLACE_THIS_WITH_REAL_SOPS_ENCRYPTION
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-15T10:00:00Z"
    mac: ENC[AES256_GCM,data:EXAMPLE_MAC,iv:EXAMPLE_IV,tag:EXAMPLE_TAG,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|token|key|secret|credentials)$
    version: 3.8.1
