---
# Example Secret
#
# Secrets store sensitive data like passwords, tokens, and keys.
# In this infrastructure, use SOPS with age to encrypt secrets before committing.
#
# Best practices:
#   1. Never commit plaintext secrets to Git
#   2. Use SOPS to encrypt secrets: sops -e secret.yaml > secret.enc.yaml
#   3. Deploy encrypted secrets: sops -d secret.enc.yaml | kubectl apply -f -
#   4. Alternatively, use external-secrets-operator with a secret provider

apiVersion: v1
kind: Secret
metadata:
  name: example-app-secret
  namespace: default
  labels:
    app: example-app
type: Opaque
stringData:
  # Database credentials
  database-username: "REPLACE_WITH_ACTUAL_USERNAME"
  database-password: "REPLACE_WITH_ACTUAL_PASSWORD"
  database-url: "postgresql://username:password@postgres:5432/myapp"

  # API keys
  api-key: "REPLACE_WITH_ACTUAL_API_KEY"
  api-secret: "REPLACE_WITH_ACTUAL_API_SECRET"

  # JWT signing key
  jwt-secret: "REPLACE_WITH_256_BIT_SECRET"

  # TLS certificates (if needed)
  # tls.crt: |
  #   -----BEGIN CERTIFICATE-----
  #   ...
  #   -----END CERTIFICATE-----
  # tls.key: |
  #   -----BEGIN PRIVATE KEY-----
  #   ...
  #   -----END PRIVATE KEY-----

---
# Using Secrets in a Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-with-secrets
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-app-with-secrets
  template:
    metadata:
      labels:
        app: example-app-with-secrets
    spec:
      containers:
        - name: app
          image: nginx:1.25-alpine

          # Method 1: Use all secret keys as environment variables
          envFrom:
            - secretRef:
                name: example-app-secret

          # Method 2: Use specific secret keys as environment variables
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: example-app-secret
                  key: database-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: example-app-secret
                  key: database-password
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: example-app-secret
                  key: api-key

          # Method 3: Mount secrets as files
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secrets
              readOnly: true
            - name: db-credentials
              mountPath: /etc/db/credentials
              readOnly: true

      volumes:
        # Mount entire secret as directory
        - name: secret-volume
          secret:
            secretName: example-app-secret
            defaultMode: 0400  # Read-only for owner

        # Mount specific secret keys as files
        - name: db-credentials
          secret:
            secretName: example-app-secret
            items:
              - key: database-username
                path: username
              - key: database-password
                path: password

---
# TLS Secret (for HTTPS ingress)
# Although Cloudflare handles TLS, you may need this for internal services

apiVersion: v1
kind: Secret
metadata:
  name: example-app-tls
  namespace: default
type: kubernetes.io/tls
stringData:
  # IMPORTANT: Replace with your actual TLS certificate and private key
  # Generate with: openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  #   -keyout tls.key -out tls.crt -subj "/CN=example.com"
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_YOUR_ACTUAL_TLS_CERTIFICATE
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_YOUR_ACTUAL_PRIVATE_KEY
    -----END PRIVATE KEY-----

---
# Docker Registry Secret (for private container registries)

apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
  # IMPORTANT: Replace with your actual Docker registry credentials
  # Or create with: kubectl create secret docker-registry docker-registry-secret \
  #   --docker-server=https://index.docker.io/v1/ \
  #   --docker-username=myuser --docker-password=mypassword \
  #   --docker-email=user@example.com
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "REPLACE_WITH_USERNAME",
          "password": "REPLACE_WITH_PASSWORD",
          "email": "REPLACE_WITH_EMAIL",
          "auth": "REPLACE_WITH_BASE64_USERNAME_PASSWORD"
        }
      }
    }

# Use in pod spec:
# spec:
#   imagePullSecrets:
#     - name: docker-registry-secret
