---
# Example Secret
#
# Secrets store sensitive data like passwords, tokens, and keys.
# In this infrastructure, use SOPS with age to encrypt secrets before committing.
#
# Best practices:
#   1. Never commit plaintext secrets to Git
#   2. Use SOPS to encrypt secrets: sops -e secret.yaml > secret.enc.yaml
#   3. Deploy encrypted secrets: sops -d secret.enc.yaml | kubectl apply -f -
#   4. Alternatively, use external-secrets-operator with a secret provider

apiVersion: v1
kind: Secret
metadata:
  name: example-app-secret
  namespace: default
  labels:
    app: example-app
type: Opaque
stringData:
  # Database credentials
  database-username: "myapp_user"
  database-password: "changeme123"
  database-url: "postgresql://myapp_user:changeme123@postgres:5432/myapp"

  # API keys
  api-key: "sk_test_xxxxxxxxxxxxx"
  api-secret: "secret_xxxxxxxxxxxxx"

  # JWT signing key
  jwt-secret: "your-256-bit-secret"

  # TLS certificates (if needed)
  # tls.crt: |
  #   -----BEGIN CERTIFICATE-----
  #   ...
  #   -----END CERTIFICATE-----
  # tls.key: |
  #   -----BEGIN PRIVATE KEY-----
  #   ...
  #   -----END PRIVATE KEY-----

---
# Using Secrets in a Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-with-secrets
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-app-with-secrets
  template:
    metadata:
      labels:
        app: example-app-with-secrets
    spec:
      containers:
        - name: app
          image: nginx:1.25-alpine

          # Method 1: Use all secret keys as environment variables
          envFrom:
            - secretRef:
                name: example-app-secret

          # Method 2: Use specific secret keys as environment variables
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: example-app-secret
                  key: database-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: example-app-secret
                  key: database-password
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: example-app-secret
                  key: api-key

          # Method 3: Mount secrets as files
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secrets
              readOnly: true
            - name: db-credentials
              mountPath: /etc/db/credentials
              readOnly: true

      volumes:
        # Mount entire secret as directory
        - name: secret-volume
          secret:
            secretName: example-app-secret
            defaultMode: 0400  # Read-only for owner

        # Mount specific secret keys as files
        - name: db-credentials
          secret:
            secretName: example-app-secret
            items:
              - key: database-username
                path: username
              - key: database-password
                path: password

---
# TLS Secret (for HTTPS ingress)
# Although Cloudflare handles TLS, you may need this for internal services

apiVersion: v1
kind: Secret
metadata:
  name: example-app-tls
  namespace: default
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDXTCCAkWgAwIBAgIJAKL0UG+mRKZfMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
    ... (certificate content) ...
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDZ8Y8mF6BvGKMB
    ... (private key content) ...
    -----END PRIVATE KEY-----

---
# Docker Registry Secret (for private container registries)

apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "myuser",
          "password": "mypassword",
          "email": "user@example.com",
          "auth": "bXl1c2VyOm15cGFzc3dvcmQ="
        }
      }
    }

# Use in pod spec:
# spec:
#   imagePullSecrets:
#     - name: docker-registry-secret
